---

- name: add repository to install php from
  apt_repository:
    repo: '{{ php_ppa_repo }}'
    update_cache: yes
  when: php_ppa_repo != None

- name: install packages
  apt:
    pkg: '{{ item }}'
    state: installed
    update_cache: yes
    cache_valid_time: 3600
  with_items: '{{ php_packages }}'